name = "studio-backend"
main = "src/index.ts"
compatibility_date = "2024-05-01"
compatibility_flags = [ "nodejs_compat" ]
[vars]
SESSION_SECRET = "placeholder"
TURNSTILE_SECRET_KEY = "placeholder"
GITHUB_TOKEN = "placeholder"
[[d1_databases]]
binding = "DB"
database_name = "engineering-studio-db"
database_id = "a8af5221-4f89-4835-acf9-268d00af3f8f"
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "engineering-studio-r2"
[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "engineering-studio-vectors"
[ai]
binding = "AI"
